### ISSUE TITLE
install

### ISSUE THREAD

**Issue by FrOoZeNBabo** [EionRobb/pidgin-win7#38]
no idea how to install this...

**Comment by oliver-graetz** [comment]
The plguin was migrated from Google Code to Github without transferring the DLL file that goes into the plugins directory. You can still get the old website through archve.org:
http://web.archive.org/web/20141225124703/https://code.google.com/p/pidgin-win7/
The download is:
http://web.archive.org/web/20110930115214/http://pidgin-win7.googlecode.com/files/pidgin-win7-5.dll

**Comment by EionRobb** [comment]
Sorry bout that, added the download to https://github.com/EionRobb/pidgin-win7/releases
